---
title: "Data Preparation"
description: |
  Generating data for model training.
author:
  - name: Kris Sankaran
    affiliation: UW Madison
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library("EBImage")
library("RStoolbox")
library("abind")
library("dplyr")
library("gdalUtils")
library("ggplot2")
library("purrr")
library("raster")
library("sf")
library("stringr")
library("tidyr")
library("tmap")
theme_set(theme_bw())
```

```{r}
data_dir <- file.path("/Users/kris/Desktop/teaching/mapping-vis/data/")
x <- brick(file.path(data_dir, "raw", "region.vrt"))
y <- read_sf(file.path(data_dir, "raw", "Glacier_2005.shp")) %>%
  filter(Sub_basin == "Kokcha")
ys <- y %>%
  split(.$Glaciers)
```

We'll train using glaciers from the Dudh Koshi basin, and test using those from
the Sun Koshi basin.

```{r}
tm_shape(y) +
  tm_fill(col = "Glaciers", palette = "Set2")
```
```{r}
coords <- y %>%
  as.data.frame() %>%
  dplyr::select(Longitude, Latitude) %>%
  as.matrix()

k_centers <- kmeans(coords, 100)$centers %>%
  as.data.frame() %>%
  mutate(type = "centroid")

coord_data <- data.frame(coords) %>%
  mutate(type = "glacier") %>%
  rbind(k_centers)

ggplot(coord_data) +
  geom_point(aes(x = Longitude, y = Latitude, col = type))
```
```{r}
equalize_input <- function(x, ...) {
  n_layers <- dim(x)[3]
  result <- array(dim = dim(x))
  
  for (l in seq_len(n_layers)) {
    cur_layer <- x[,, l]
    cur_layer <- cur_layer - min(cur_layer)
    cur_layer <- cur_layer / max(cur_layer)
    result[,, l] <- EBImage::equalize(cur_layer, ...)
  }
  
  result
}

impute_na <- function(x, val = 0) {
  x[is.na(x)] <- val
  x
}

read_subset <- function(x_path, te, band_names = NULL) {
  tmp <- tempfile()
  gdalbuildvrt(x_path, tmp, te = te)
  result <- brick(tmp)
  if (!is.null(band_names)) {
    names(result) <- band_names
  }
  
  result
}

generate_patch <- function(x_path, center, max_na = 0.2, subset_inputs=NULL) {
  if (is.null(subset_inputs)) {
    subset_inputs <- c(1:5, 7:9, 11:15)
  }
  
  point <- st_point(center, dim = "XY") %>%
    st_buffer(0.1) %>%
    st_geometry()
  
  x_raster <- read_subset(x_path, st_bbox(point))
  x <- x_raster %>%
    as.array()
  x <- x[,, subset_inputs]
  if (mean(is.na(x)) < max_na) {
    x <- impute_na(x) %>%
      equalize_input(range = c(-1, 1))
  } else {
    return()
  }
  
  list(x = x, meta = point, raster = x_raster)
}

label_mask <- function(ys, x_raster) {
  box <- extent(x_raster) %>%
    st_bbox()
 
  rasterize_ <- function(z, p) {
    if (nrow(z) == 0) {
      return (array(0, c(dim(p)[1:2], 1)))
    }
    rasterize(z, p) %>%
      as.array()
  }
  
  y_ <- map(ys, ~ st_crop(., box) %>% st_zm()) %>%
    map(~ rasterize_(., x_raster)) %>%
    abind()
  
  y_[!is.na(y_)] <- 1
  y_[is.na(y_)] <- 0
  y_
}

write_patches <- function(x_path, ys, centers, out_dir) {
  unlink(out_dir)
  dir.create(out_dir)
  
  j <- 1
  geo <- list()
  for (i in seq_len(nrow(centers))) {
    patch <- generate_patch(x_path, centers[i, ])
    
    # if not too many NAs, get mask and crop
    if (!is.null(patch)) {
      y <- label_mask(ys, patch$raster)
      x <- patch$x
      
      # save results
      save(x, file = file.path(out_dir, str_c("x-", j, ".RData")))
      save(y, file = file.path(out_dir, str_c("y-", j, ".RData")))
      write_sf(patch$meta, file.path(out_dir, str_c("geo-", j, ".geojson")))
      j <- j + 1
    }
  }
}
```

```{r}
x_path <- file.path(data_dir, "raw", "region.vrt")
k_mat <- k_centers %>%
  dplyr::select(Longitude, Latitude) %>%
  as.matrix()
write_patches(x_path, ys, k_mat, file.path(data_dir, "processed"))
```
