---
title: "Train on Preprocessed Data"
output: html_notebook
params:
  data_dir: "/Users/kris/Desktop/teaching/mapping-vis/data/processed/"
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library("RStoolbox")
library("ggplot2")
library("mappingvis")
library("raster")
library("torch")
library("torchvision")
library("zeallot")
```

```{r}
glacier_data <- dataset(
  name = "glaciers",
  initialize = initializer,
  .getitem = getitem,
  .length = function() { nrow(self$paths) }
)
```

```{r}
data_dir <- params$data_dir
x_paths <- list.files(data_dir, "x-*", full = TRUE)
y_paths <- list.files(data_dir, "y-*", full = TRUE)
ds <- glacier_data(x_paths, y_paths)
```

```{r}
ix <- 1
batch <- ds[ix]

ggRGB(to_raster(batch[[1]]), r = 5, 4, 2)
ggRGB(to_raster(batch[[1]]), r = 13, g = 12, b = 12)
ggRGB(to_raster(batch[[2]]))
```

```{r}
loaders <- list(
  "train" = dataloader(ds, batch_size=2), 
  "test" = dataloader(ds, batch_size=2)
)
```

```{r}
n_epoch <- 20
device <- torch_device(if(cuda_is_available()) "cuda" else "cpu")
model <- initialize_unet(device = device)
opt <- optim_sgd(model$parameters, lr = 0.1, momentum = 0.9)
scheduler <- lr_one_cycle(opt, max_lr = 0.1, steps = length(loaders$train), epochs = n_epoch)

losses <- list(
  "train" = matrix(nrow = n_epoch, ncol = length(loaders$train)),
  "test" = matrix(nrow = n_epoch, ncol = length(loaders$test))
)

for (i in seq_len(n_epoch)) {
  c(model, opt, scheduler, l) %<-% train_epoch(model, opt, loaders, scheduler, device)
  print(mean(l$train))
  losses$train[i, ] <- l$train
  losses$test[i, ] <- l$test
}
```
